"""Content for every Haus Techs landing page.

Edit copy, photos, calculator rates and FAQs here, then run build.py.
Copy follows the brand voice (considered, quiet, precise) and uses no em-dashes.
Facts (200+ projects, 4+ years, reviews, prices, timelines) come from the live pages;
do not add claims the business has not confirmed.
"""
from urllib.parse import quote as q

CONTACT = {
    "tel": "+971562990062",
    "tel_disp": "+971 56 299 0062",
    "wa": "971562990062",
    "email": "info@haustechs.ae",
}


def wa(text):
    return "https://wa.me/971562990062?text=" + q(text, safe="")


WP = "https://haustechs.ae/wp-content/uploads/"

# ------------------------------------------------------------------ shared English strings
T_EN = {
    "skip": "Skip to content",
    "call": "Call",
    "nav_cta": 'Get my <span class="lbl-long">fixed </span>quote',
    "quote_short": "Quote",
    "wa_cta": "WhatsApp us",
    "calc_cta": "Estimate my cost",
    "rating": "Rated 5.0 by Dubai {who} on {google}",
    "proof_label": "Haus Techs in numbers",
    "promises_label": "What every project includes",
    "stats": [(4, "+", "Years in Dubai"), (200, "+", "Projects delivered"), (50, "+", "Team members"), (15, "+", "Years combined expertise")],
    "calc_h": 'Know your number <span class="it">in 30 seconds.</span>',
    "calc_lede": "An instant estimate range now, then a fixed-price quotation within 48 hours with a free 3D design concept.",
    "calc_ticks": [
        "Instant range based on real Haus Techs project rates",
        "Fixed-scope quotation: the number you see is the number you pay",
        "Free 3D design concept with every quotation",
        "Workmanship warranty on every project",
    ],
    "calc_mode": "Estimate type",
    "mode_reno": "Renovation cost",
    "mode_design": "Design only",
    "ptype": "Property type",
    "size": "Approximate size",
    "unit": "sqm",
    "finish": "Finish level",
    "finishes": [("standard", "Standard", "Quality essentials"), ("premium", "Premium", "Our signature"), ("luxury", "Luxury", "Statement finish")],
    "est_reno": "Estimated renovation cost",
    "est_design": "Estimated design fee (concept, 3D and drawings)",
    "cur": "AED",
    "calc_note": "Indicative range. Your fixed quotation follows a free site visit.",
    "calc_wa": "Send this estimate on WhatsApp",
    "j_kicker": "How we handle your project",
    "j_h2a": "One team. One journey.",
    "j_h2b": "Zero surprises.",
    "j_lede": "From first message to handover: exactly what happens, what you do, and what we take off your plate.",
    "you_do": "You do",
    "we_do": "We do",
    "journey": None,  # filled below
    "view": "View photo",
    "close": "Close",
    "prev": "Previous photos",
    "next": "Next photos",
    "g_review": "Google review",
    "v_h2": "Why our clients stop comparing.",
    "v_lede": "Most renovation quotes look similar on paper. The experience behind them is not.",
    "v_old_h": "The usual way",
    "v_new_h": "The Haus Techs way",
    "v_old": [
        "Several contractors, nobody fully responsible",
        "Per-day pricing, so the number grows as you go",
        "You chase updates while they chase payments",
        "Approvals and permits become your problem",
        "Handover, then silence when snags appear",
    ],
    "v_new": [
        "One contract, one team, one project manager",
        "Fixed-scope price in 48 hours. The number you see is the number you pay.",
        "A free 3D concept before you commit, weekly updates during",
        "All approvals, NOCs and permits handled by us",
        "Workmanship warranty and a snag visit after handover",
    ],
    "promise": "Done once, properly. That is the whole promise.",
    "q_kicker": "Get your quote",
    "q_lede": "Send your details and our team replies the same working day with next steps and a site visit slot. Your enquiry goes straight to our project desk.",
    "visit": "Book a free site visit",
    "visit_sub": "Pick a time with us on WhatsApp",
    "email_l": "Email us",
    "form_h": "Your fixed quote in 48 hours",
    "form_sub": "Free site visit, free 3D design concept, no obligation.",
    "name": "Your name",
    "name_ph": "Full name",
    "phone": "Phone / WhatsApp",
    "email": "Email",
    "contact": "Preferred contact",
    "contact_opts": ["WhatsApp", "Call", "Email"],
    "optional": "(optional)",
    "message": "Message",
    "message_ph": "Anything you'd like our team to know?",
    "submit": "Get my fixed quote",
    "or": "or",
    "send_wa": "Send via WhatsApp instead",
    "form_note": "We reply the same working day. Your details are only used to prepare your quote.",
    "err_name": "Please add your name.",
    "err_phone": "Please add a phone number we can reach you on.",
    "err_email": "That email address doesn't look complete.",
    "err_location": "Please tell us where the property is.",
    "faq_h": "Before you ask.",
    "final_lede": "Free consultation, free site visit, and a detailed fixed-scope quotation.",
    "company": "Haus Techs Technical Contracting LLC",
    "address": "Princess Cars Building, Office 14-27, Sheikh Zayed Rd, next to Oasis Mall, Al Quoz First, Dubai, U.A.E.",
    "tagline": "Design · Build · Turnkey",
    "quick": "Quick contact",
    "before": "Before",
    "after": "After",
    "ba_slider": "Drag to compare before and after",
    "play": "Watch the video",
}


CREW = [("work/crew-cladding", "Haus Techs installer fixing wall cladding"),
        ("work/crew-level", "Haus Techs installer checking a wall panel with a spirit level"),
        ("work/crew-joinery", "Haus Techs carpenter fitting kitchen joinery")]


def concepts_block(lede, figs):
    return {"h2a": "Your free 3D concept.", "h2b": "Before you commit.", "lede": lede, "figs": figs}


def journey_en(approvals_title, approvals_we):
    return [
        {"when": "Day 0", "h3": "You reach out", "p": "Form, WhatsApp or the cost calculator, whichever suits you.",
         "you": "Two minutes of your time.", "we": "We reply the same working day and book your free site visit."},
        {"when": "Within days", "h3": "Site visit and brief", "p": "We walk the space with you and listen to how you actually live and work in it.",
         "you": "Show us the space. Tell us the dream.", "we": "We measure everything and advise honestly, including what not to spend on."},
        {"when": "48 hours", "h3": "Fixed quote and free 3D concept", "p": "One clear number and a 3D concept of your space, before you commit to anything.",
         "you": "Review one detailed, fixed-scope quotation.", "we": "Full scope, real numbers, free 3D design concept. No per-day pricing, ever."},
        {"when": "We handle it", "h3": approvals_title, "p": "Paperwork is our job, not yours.",
         "you": "Nothing. Genuinely nothing.", "we": approvals_we},
        {"when": "The build", "h3": "One team on site", "p": "Our own crews, one project manager, a fixed timeline.",
         "you": "A weekly update from one person you know by name.", "we": "In-house execution, daily supervision, dust and noise control. No subcontractor chaos.",
         "photos": CREW, "photos_cap": "Our own crews on site, Living Legends villa renovation."},
        {"when": "Handover", "h3": "Done, and covered", "p": "Snag-free handover with our workmanship warranty behind it.",
         "you": "Move in and live.", "we": "A final walkthrough together, the warranty in writing, and we come back if anything ever needs us."},
    ]


REV = {
    "yusuf": ("Haus Techs transformed our villa beautifully. From planning to execution, everything was handled with care and precision.", "Yusuf Al-Hamdan"),
    "ivan": ("The quality of their work is truly outstanding. Everything was executed with precision. Fair prices and high quality of work.", "Ivan Jeremic"),
    "obaid": ("The team was professional, punctual, and highly skilled. Communication was excellent throughout the entire process.", "Obaid Al Saboosi"),
    "jamshaid": ("They were on time, worked efficiently, and cleaned up after themselves each day. Highly recommended!", "Jamshaid Munir Sandhu"),
    "burj": ("Haus Techs did an excellent job with our interiors: stylish, functional, and exactly what we needed. Highly recommended.", "Burj Blizz"),
}


def form_wa_js(kind_line, loc_label, detail_label):
    # JS function body used by the "Send via WhatsApp" button on each form
    return (
        "function(d){return \"Hi Haus Techs, " + kind_line + "\\nName: \"+d.name+\"\\nPhone: \"+d.phone+\"\\n"
        + loc_label + ": \"+d.location+\"\\n" + detail_label + ": \"+d.detail+(d.message?\"\\nNote: \"+d.message:\"\");}"
    )


CALC_WA_EN = (
    "function(type,sqm,finish,est){return \"Hi Haus Techs, I used your cost calculator.\\nType: \"+type+\"\\nSize: \"+sqm+\" sqm\\nFinish: \"+finish+\"\\nEstimate: \"+est+\"\\nI'd like my fixed quote.\";}"
)

FAQ_TAIL = [
    ("Is there a warranty?", "Yes. Our workmanship is covered by warranty, and we return to resolve any snags after handover."),
]

# ------------------------------------------------------------------ villa
VILLA = {
    "file": "villa-renovation-dubai.html", "lang": "en", "T": T_EN,
    "title": "Full Villa Renovation in Dubai | Haus Techs",
    "desc": "Full villa renovation in Dubai delivered by one team with one project manager. Design, approvals, execution and handover. 200+ projects delivered.",
    "subject": "New Villa Renovation Lead — Google Ads",
    "source": "Villa Renovation landing page (Google Ads)",
    "wa_url": wa("Hi Haus Techs, I'm planning a full villa renovation in Dubai and would like a quote."),
    "visit_url": wa("Hi Haus Techs, I'd like to book a free site visit for my villa renovation."),
    "rating_who": "homeowners",
    "hero": {
        "kicker": "Villa renovation, Dubai",
        "h1a": "Full villa renovation.", "h1b": "One team, start to finish.",
        "sub": "Design, approvals, build and handover under one contract, one project manager and a fixed price.",
        "img": WP + "2025/04/Living-Legends-scaled.jpg", "img_alt": "Villa living room renovated by Haus Techs in Dubai",
    },
    "promises": ["Fixed-price quote within 48 hours", "Free 3D design concept with every quotation", "One project manager",
                 "Workmanship warranty on every project", "Full renovations only", "In-house design and execution"],
    "calc": {"kicker": "Villa cost calculator", "types": ["Villa", "Townhouse"], "range": (200, 1200, 10, 400),
             "rates": {"Villa": {"standard": 1800, "premium": 2400, "luxury": 3200}, "Townhouse": {"standard": 1700, "premium": 2200, "luxury": 3000}},
             "min": {"Villa": 200000, "Townhouse": 160000}},
    "calc_wa_js": CALC_WA_EN,
    "form": {"location_label": "Community / location", "location_ph": "e.g. Arabian Ranches, Jumeirah Park",
             "detail_label": "Villa size", "detail_opts": ["3 bedrooms", "4 bedrooms", "5 bedrooms", "6+ bedrooms"]},
    "form_wa_js": form_wa_js("I'd like a quote for a full villa renovation.", "Community / location", "Villa size"),
    "included": {
        "h2": "Everything a full villa renovation should include.",
        "lede": "One contract, one price, one team accountable for the entire villa, inside and out.",
        "tiles": [
            ("work/c-villa-lounge", "3D design concept of an open-plan villa lounge", "Design and space planning",
             "Concepts, 3D visualisation and finish selection led by our in-house design head, re-planned around how you actually live."),
            (WP + "2025/06/villa-renovation-2.jpg", "Villa renovation in progress", "Approvals and permits",
             "Community, developer and authority approvals, drawings, NOCs and permits. Handled by us."),
            ("work/g17-living", "Finished villa living area with herringbone floor, G17 Al Waha", "Civil, structural and finishing",
             "Wall changes, extensions, flooring, tiling and gypsum, supervised and snag-checked by our own teams."),
            ("work/v91-shower", "Finished travertine shower room, Villa 91 Al Ain", "Kitchens and bathrooms",
             "Bespoke joinery, premium stone, sanitary ware and fixtures from trusted brand partners."),
            ("work/g17-bedroom-2", "Bedroom with cove lighting and concealed AC, G17 Al Waha", "MEP: electrical, plumbing, AC",
             "Complete rewiring, plumbing, AC ducting and smart-home provisions brought up to current standards."),
            (WP + "2025/06/interior-design-services-uae.jpg", "Villa outdoor living", "Outdoor and landscape",
             "Pools, pergolas, outdoor kitchens, boundary walls and landscaping that match the interior finish."),
        ],
    },
    "journey": journey_en("Approvals and permits, done",
                          "Community, developer and authority approvals: drawings, NOCs and permits, all secured by our team."),
    "before_after": {
        "h2a": "G17, Al Waha.", "h2b": "Before and after.",
        "lede": "A full villa renovation delivered by our own team. Drag the line to compare the same rooms before we started and at handover.",
        "note": "Real site photos from the project, not renders.",
        "pairs": [("Bedroom", "work/g17-before-bedroom-2", "work/g17-bedroom", "bedroom with French doors, G17 Al Waha"),
                  ("Suite", "work/g17-before-bedroom", "work/g17-bedroom-wardrobe", "bedroom with built-in wardrobe, G17 Al Waha"),
                  ("Bathroom", "work/g17-before-bath", "work/g17-after-bath", "bathroom, G17 Al Waha")],
    },
    "work": {"h2": "Villas we've delivered.", "lede": "Real photos from finished projects, including Villa 91 in Al Ain and G17 in Al Waha. Tap any photo to view.",
             "figs": [
                 ("work/v91-shower", "Villa 91, Al Ain: master shower in travertine", ""),
                 ("work/g17-bedroom-wardrobe", "G17, Al Waha: bedroom and wardrobe joinery", ""),
                 ("work/v91-bath-vanity", "Villa 91, Al Ain: floating vanity and walk-in shower", ""),
                 ("work/g17-living", "G17, Al Waha: living area and herringbone floor", ""),
                 ("work/v91-vanity", "Villa 91, Al Ain: vessel basin and mirror", ""),
                 ("work/g17-bathtub", "G17, Al Waha: bathtub with cove lighting", ""),
                 ("work/v91-shower-2", "Villa 91, Al Ain: frameless glass shower", ""),
                 ("work/v91-hall", "Villa 91, Al Ain: upper hall with pool view", ""),
                 (WP + "2025/06/villa-renovation.jpg", "Completed renovation, Dubai", ""),
             ]},
    "concepts": concepts_block("Every quotation includes a 3D design concept of your villa, so you see the result before any work starts. Recent concepts from our studio:", [
        ("work/c-villa-living", "3D concept: double-height living room"),
        ("work/c-villa-bedroom", "3D concept: master bedroom"),
        ("work/c-villa-vanity", "3D concept: marble vanity"),
        ("work/c-villa-dining", "3D concept: dining room"),
        ("work/c-villa-bedroom-2", "3D concept: private villa bedroom"),
        ("work/c-barari-living", "3D concept: Al Barari villa living room"),
    ]),
    "reviews": {"h2": "What homeowners say.", "items": [REV["yusuf"], REV["ivan"], REV["obaid"]]},
    "band": {"h2a": "Your villa, done once.", "h2b": "Properly.",
             "p": "Every project gets a dedicated project manager, transparent pricing and a fixed completion date.",
             "img": WP + "2025/06/villa-interior.jpg", "img_alt": "Renovated villa interior",
             "gains_h": "A renovation that pays you back.",
             "gains": [("Higher resale value", "A professionally renovated villa commands a premium in Dubai's fast-moving market."),
                       ("Lower running costs", "Modern AC, insulation and lighting cut energy bills for years."),
                       ("A home built around you", "Layouts re-planned for how your family lives, not how the developer built it."),
                       ("Warranty and aftercare", "Our workmanship is covered after handover, and we return for any snags.")]},
    "quote": {"h2": "Tell us about your villa."},
    "faq": [
        ("How much does a full villa renovation cost in Dubai?", "It depends on size and finish level. Most full villa renovations we deliver start from AED 200,000, with premium and luxury scopes going well beyond that. After a site visit you receive a detailed, fixed-scope quotation, never vague per-day pricing."),
        ("How long does it take?", "A typical full villa renovation runs 8 to 16 weeks depending on scope and approvals. Your project manager gives you a timeline before work starts and weekly updates throughout."),
        ("Do you handle community and authority approvals?", "Yes. Drawings, NOCs and permits are part of our scope. You don't chase developers or authorities yourself."),
        ("Can I live in my villa during the renovation?", "For full villa renovations we recommend relocating temporarily. It's faster, safer and more comfortable, especially during structural and MEP works. Your project manager will advise based on your scope."),
        ("Do you take on small jobs like painting or single-room work?", "No. We focus on full renovations only, which is how we keep dedicated crews and consistent quality on every project."),
    ] + FAQ_TAIL,
    "final": "Ready to transform your villa?",
}

# ------------------------------------------------------------------ apartment
APARTMENT = {
    "file": "apartment-renovation-dubai.html", "lang": "en", "T": T_EN,
    "title": "Apartment Renovation in Dubai | Haus Techs",
    "desc": "Full apartment renovation in Dubai: design, building NOCs, execution and handover by one team with one project manager. 200+ projects delivered.",
    "subject": "New Apartment Renovation Lead — Google Ads",
    "source": "Apartment Renovation landing page (Google Ads)",
    "wa_url": wa("Hi Haus Techs, I'm planning a full apartment renovation in Dubai and would like a quote."),
    "visit_url": wa("Hi Haus Techs, I'd like to book a free site visit for my apartment renovation."),
    "rating_who": "homeowners",
    "hero": {
        "kicker": "Apartment renovation, Dubai",
        "h1a": "Full apartment renovation.", "h1b": "One team, start to finish.",
        "sub": "Design, building NOCs, build and handover under one contract, with tower logistics handled properly.",
        "img": "lp-images/design-13.jpg", "img_alt": "Apartment living room designed by Haus Techs in Dubai",
    },
    "promises": ["Fixed-price quote within 48 hours", "Free 3D design concept with every quotation", "One project manager",
                 "Building NOCs handled", "Workmanship warranty on every project", "Full renovations only"],
    "calc": {"kicker": "Apartment cost calculator", "types": ["Apartment", "Penthouse"], "range": (60, 500, 10, 140),
             "rates": {"Apartment": {"standard": 1600, "premium": 2100, "luxury": 2800}, "Penthouse": {"standard": 1900, "premium": 2500, "luxury": 3400}},
             "min": {"Apartment": 100000, "Penthouse": 150000}},
    "calc_wa_js": CALC_WA_EN,
    "form": {"location_label": "Building / community", "location_ph": "e.g. Dubai Marina, Downtown, JBR",
             "detail_label": "Apartment size", "detail_opts": ["Studio / 1 bedroom", "2 bedrooms", "3 bedrooms", "4 bedrooms / Penthouse"]},
    "form_wa_js": form_wa_js("I'd like a quote for a full apartment renovation.", "Building / community", "Apartment size"),
    "included": {
        "h2": "Everything a full apartment renovation should include.",
        "lede": "One contract, one price, one team accountable for your entire apartment, from drawings to snag-free handover.",
        "tiles": [
            ("work/c-apt-living", "3D design concept of an apartment living room, BLVD Heights Downtown Dubai", "Design and space planning",
             "Layout re-planning, concepts, 3D visualisation and finish selection that make every square metre work harder."),
            (WP + "2025/06/apartment-renovation-5.jpg", "Apartment approvals", "Building NOCs and permits",
             "Building management approvals, developer NOCs and permits, with drawings. Secured by us."),
            (WP + "2025/06/apartment-renovation-6.jpg", "Apartment finishing works", "Civil and finishing works",
             "Walls, flooring, tiling, gypsum ceilings, painting and complete finishing, snag-checked by our own teams."),
            (WP + "2025/06/bathroom-interior-design.jpg", "Renovated bathroom", "Kitchens and bathrooms",
             "Bespoke joinery, premium stone, sanitary ware and fixtures from trusted brand partners."),
            (WP + "2025/06/kitchen-interior-design.jpg", "Apartment kitchen", "MEP: electrical, plumbing, AC",
             "Rewiring, plumbing, AC works and smart-home provisions brought up to current standards."),
            (WP + "2025/03/bedroom-1.webp", "Bedroom joinery", "Joinery and built-ins",
             "Wardrobes, TV units, feature walls and custom storage designed to maximise space in tower living."),
        ],
    },
    "journey": journey_en("Building NOCs, done",
                          "Building management approvals and developer NOCs: drawings prepared, submitted and secured by our team."),
    "work": {"h2": "Apartments we've transformed.", "lede": "Real projects, delivered by our own teams. Tap any photo to view.",
             "figs": [
                 ("lp-images/design-13.jpg", "Grand living, signature interior design", ""),
                 ("lp-images/design-14.jpg", "Master bedroom design", ""),
                 ("lp-images/design-03.jpg", "Double-height living room", ""),
                 ("lp-images/design-15.jpg", "Dressing room and vanity", ""),
                 ("lp-images/design-17.jpg", "Bespoke wardrobe joinery", ""),
                 ("lp-images/design-05.jpg", "Living room with a travertine feature wall", ""),
                 ("lp-images/design-18.jpg", "Bedroom, full design", ""),
                 ("lp-images/design-11.jpg", "Living space, full layout", ""),
             ]},
    "concepts": concepts_block("Every quotation includes a 3D design concept of your apartment. Here is one from BLVD Heights in Downtown Dubai, plus recent concepts from our studio:", [
        ("work/c-apt-living", "3D concept: BLVD Heights, Downtown Dubai, living room"),
        ("work/c-apt-bedroom", "3D concept: BLVD Heights, master bedroom"),
        ("work/c-apt-kitchen", "3D concept: BLVD Heights, kitchen and dining"),
        ("work/c-apt-dining", "3D concept: open-plan dining"),
        ("work/c-apt-lounge", "3D concept: lounge"),
        ("work/c-apt-shower", "3D concept: shower room"),
    ]),
    "reviews": {"h2": "What homeowners say.", "items": [REV["obaid"], REV["ivan"], REV["jamshaid"]]},
    "band": {"h2a": "Tower rules, service lifts, working hours.", "h2b": "We handle the building.",
             "p": "Dust control, noise management and neighbour-friendly scheduling on every apartment project.",
             "img": WP + "2025/06/apartment-renovation-6.jpg", "img_alt": "Renovated apartment interior",
             "gains_h": "A renovation that pays you back.",
             "gains": [("Higher rental and resale value", "Renovated apartments command a clear premium in Dubai's rental and sales market."),
                       ("Space that works harder", "Layout re-planning and built-in joinery add usable space without adding square metres."),
                       ("Lower running costs", "Modern AC, appliances and lighting cut energy bills for years."),
                       ("Warranty and aftercare", "Our workmanship is covered after handover, and we return for any snags.")]},
    "quote": {"h2": "Tell us about your apartment."},
    "faq": [
        ("How much does a full apartment renovation cost in Dubai?", "It depends on size and finish level. Most full apartment renovations we deliver start from AED 100,000, with premium and luxury scopes going beyond that. After a site visit you receive a detailed, fixed-scope quotation, never vague per-day pricing."),
        ("How long does it take?", "A typical full apartment renovation runs 6 to 10 weeks depending on scope and building approvals. Your project manager gives you a timeline before work starts and weekly updates throughout."),
        ("Do you handle building management NOCs?", "Yes. Drawings, building management approvals and developer NOCs are part of our scope. You don't chase anyone yourself."),
        ("Can I live in my apartment during the renovation?", "For full renovations we recommend relocating temporarily. It's faster, safer and more comfortable. Your project manager will advise based on your scope."),
        ("Do you take on small jobs like painting or single-room work?", "No. We focus on full renovations only, which is how we keep dedicated crews and consistent quality on every project."),
    ] + FAQ_TAIL,
    "final": "Ready to transform your apartment?",
}

# ------------------------------------------------------------------ palm
PALM = {
    "file": "palm-jumeirah-renovation.html", "lang": "en", "T": T_EN,
    "title": "Palm Jumeirah Renovation Specialists | Haus Techs",
    "desc": "Renovation specialists for Palm Jumeirah: Garden Homes, Signature Villas, Shoreline and Golden Mile apartments. Full renovations, kitchens, bathrooms and outdoor living, with Nakheel and Trakhees approvals handled.",
    "subject": "New Palm Jumeirah Lead — Google Ads",
    "source": "Palm Jumeirah landing page (Google Ads)",
    "wa_url": wa("Hi Haus Techs, I'm planning a renovation on Palm Jumeirah and would like a quote."),
    "visit_url": wa("Hi Haus Techs, I'd like to book a free site visit for my home on Palm Jumeirah."),
    "rating_who": "homeowners",
    "hero": {
        "kicker": "Palm Jumeirah renovation",
        "h1a": "Renovating homes on the Palm.", "h1b": "Villas, apartments, everything inside.",
        "sub": "Garden Homes to Shoreline. Full renovations, kitchens, bathrooms and outdoor living, with Nakheel and Trakhees approvals handled.",
        "img": WP + "2025/05/villa-interior-design-in-dubai-.jpg", "img_alt": "Luxury home renovation on Palm Jumeirah by Haus Techs",
    },
    "promises": ["Villas, townhomes and apartments", "Nakheel and Trakhees approvals", "Delivered projects on the Palm",
                 "Fixed-price quote within 48 hours", "Free 3D design concept with every quotation", "Workmanship warranty on every project"],
    "calc": {"kicker": "Palm Jumeirah cost calculator", "types": ["Palm Villa", "Palm Apartment"], "range": (80, 1400, 10, 450),
             "rates": {"Palm Villa": {"standard": 2000, "premium": 2700, "luxury": 3600}, "Palm Apartment": {"standard": 1800, "premium": 2300, "luxury": 3100}},
             "min": {"Palm Villa": 300000, "Palm Apartment": 120000}},
    "calc_wa_js": CALC_WA_EN,
    "form": {"location_label": "Where on the Palm?", "location_ph": "e.g. Frond G Garden Homes, Shoreline Apt 5",
             "detail_label": "Type of work", "detail_opts": ["Full villa renovation", "Full apartment renovation", "Kitchen renovation", "Bathroom renovation", "Outdoor / landscape"]},
    "form_wa_js": form_wa_js("I'd like a quote for a renovation on Palm Jumeirah.", "Where on the Palm", "Type of work"),
    "communities": {
        "h2a": "One island. Every community.", "h2b": "One team.",
        "lede": "The Palm has its own rules, its own approvals and its own logistics. We know them, community by community.",
        "items": [
            ("Garden Homes", "Full villa transformations on the fronds: interiors, pools and beachfront gardens, with frond access logistics handled."),
            ("Signature Villas", "Large-scale renovations for the Palm's grandest homes: structural work, luxury finishes and outdoor living."),
            ("Canal Cove", "Townhouse renovations that maximise space and light: kitchens, bathrooms and full interior rebuilds."),
            ("Shoreline Apartments", "Full apartment renovations on the trunk. We've delivered here, and building management knows our teams."),
            ("Golden Mile, Tiara and Oceana", "Trunk residences renovated with tower rules, service lifts and working hours managed end to end."),
            ("The Crescent", "Penthouse and residence renovations on the crescent, finished to hotel-grade standards."),
        ],
    },
    "included": {
        "h2": "Every type of residential work, under one roof.",
        "lede": "A complete villa transformation or the heart of an apartment. One team, one project manager, one fixed scope.",
        "tiles": [
            (WP + "2025/06/villa-renovation.jpg", "Full villa renovation", "Full villa renovation",
             "Garden Homes, Signature Villas and Canal Cove townhomes: interiors, exteriors and structure, finished to the standard the address expects."),
            (WP + "2025/06/apartment-renovation-7.jpg", "Apartment renovation", "Apartment renovation",
             "Shoreline, Golden Mile, Tiara, Oceana and the newer towers, with building logistics handled."),
            (WP + "2025/06/kitchen-interior-design.jpg", "Kitchen renovation", "Kitchen renovation",
             "Custom joinery, stone counters, appliances and lighting. Kitchens built for entertaining."),
            (WP + "2025/06/bathroom-interior-design.jpg", "Bathroom renovation", "Bathroom renovation",
             "Complete bathroom rebuilds: waterproofing, stone work, sanitary ware and fixtures."),
            (WP + "2025/06/interior-design-services-uae.jpg", "Outdoor living", "Outdoor living and landscape",
             "Pools, decks, pergolas, outdoor kitchens and beachfront garden landscaping for villa plots."),
            (WP + "2025/06/villa-renovation-2.jpg", "Approvals", "Nakheel and Trakhees approvals",
             "The Palm has its own approval process. We prepare the drawings, submit the NOCs and secure the permits, so your project never stalls."),
        ],
    },
    "journey": journey_en("Nakheel and Trakhees, done",
                          "The Palm's own approval process: drawings, NOCs and permits with Nakheel, Trakhees and building management, all secured by us."),
    "work": {"h2": "Homes we've transformed.", "lede": "Real projects, delivered by our own teams. Tap any photo to view.",
             "figs": [
                 (WP + "2025/06/apartment-renovation-7.jpg", "Shoreline Apartments renovation, Palm Jumeirah", ""),
                 (WP + "2025/06/villa-interior-design-in-dubai.jpg", "Luxury villa interior", ""),
                 (WP + "2025/06/villa-renovation.jpg", "Full villa transformation", ""),
                 (WP + "2025/06/kitchen-interior-design.jpg", "Kitchen renovation", ""),
                 (WP + "2025/06/bathroom-interior-design.jpg", "Bathroom renovation", ""),
                 (WP + "2025/06/villa-renovation-2.jpg", "Villa renovation, living spaces", ""),
                 (WP + "2025/06/bathroom-cover.jpg", "Master bathroom rebuild", ""),
                 ("lp-images/design-09.jpg", "Double-height living, signature design", ""),
                 ("lp-images/design-13.jpg", "Grand living, interior design", ""),
                 ("lp-images/design-14.jpg", "Master bedroom design", ""),
             ]},
    "video": {"h2a": "Shoreline Apartments,", "h2b": "Palm Jumeirah.",
              "lede": "A renovation we delivered on the trunk of the Palm. Watch the project video.",
              "drive_id": "1DAEDsUVTi24XXEagK0lyRqsTTbo-XYhr",
              "poster": WP + "2025/06/apartment-renovation-7.jpg", "poster_alt": "Shoreline Apartments renovation, Palm Jumeirah"},
    "concepts": concepts_block("Every quotation includes a 3D design concept of your home on the Palm. Recent concepts from our studio:", [
        ("work/c-villa-living-2", "3D concept: double-height living with fireplace"),
        ("work/c-villa-suite", "3D concept: master suite"),
        ("work/c-villa-lounge", "3D concept: open-plan lounge"),
        ("work/c-barari-kitchen", "3D concept: villa kitchen"),
        ("work/c-villa-bath", "3D concept: bathroom"),
        ("work/c-villa-bedroom", "3D concept: bedroom"),
    ]),
    "reviews": {"h2": "What homeowners say.", "items": [REV["yusuf"], REV["obaid"], REV["ivan"]]},
    "band": {"h2a": "The Palm has its own rules.", "h2b": "We know them.",
             "p": "Nakheel and Trakhees approvals prepared, submitted and secured by our team, so your project never stalls.",
             "img": WP + "2025/06/villa-interior-design-in-dubai.jpg", "img_alt": "Palm Jumeirah villa interior",
             "gains_h": "On the Palm, quality is the investment.",
             "gains": [("Address-level finish", "Materials and workmanship that hold up to Palm Jumeirah standards and buyer expectations."),
                       ("Higher resale and rental value", "Professionally renovated Palm homes command a clear premium."),
                       ("Approvals without delays", "Nakheel and Trakhees processes handled by a team that has done it before."),
                       ("Warranty and aftercare", "Our workmanship is covered after handover, and we return for any snags.")]},
    "quote": {"h2": "Tell us about your home on the Palm."},
    "faq": [
        ("How much does a renovation on Palm Jumeirah cost?", "It depends on the scope. Full villa renovations on the Palm typically start from AED 300,000 and full apartment renovations from AED 120,000. Kitchen and bathroom renovations are quoted per scope. After a site visit you receive a detailed, fixed-scope quotation."),
        ("How long does it take?", "Kitchens and bathrooms run 3 to 6 weeks, full apartments 6 to 10 weeks, and full villas 10 to 16 weeks depending on scope and approvals. Your project manager gives you a timeline before work starts."),
        ("Do you handle Nakheel and Trakhees approvals?", "Yes. Drawings, NOCs and permits with Nakheel, Trakhees and building management are part of our scope. You don't chase anyone yourself."),
        ("Can I live in my home during the renovation?", "For kitchens and bathrooms, usually yes. For full renovations we recommend relocating temporarily. Your project manager will advise based on your scope."),
        ("Do you take on kitchens and bathrooms as standalone projects on the Palm?", "Yes. On Palm Jumeirah we take on full villa and apartment renovations as well as substantial kitchen, bathroom and outdoor living projects."),
    ] + FAQ_TAIL,
    "final": "Ready to transform your home on the Palm?",
}

# ------------------------------------------------------------------ commercial
COMMERCIAL = {
    "file": "commercial-fitout-dubai.html", "lang": "en", "T": T_EN,
    "title": "Office & Retail Fitout in Dubai | Haus Techs",
    "desc": "Turnkey office and retail fitout in Dubai: design, authority approvals, execution and on-schedule handover by one team. Offices, stores, F&B and showrooms.",
    "subject": "New Commercial Fitout Lead — Google Ads",
    "source": "Commercial Fitout landing page (Google Ads)",
    "wa_url": wa("Hi Haus Techs, I'm planning an office or retail fitout in Dubai and would like a quote."),
    "visit_url": wa("Hi Haus Techs, I'd like to book a free site visit for a commercial fitout."),
    "rating_who": "clients",
    "hero": {
        "kicker": "Office and retail fitout, Dubai",
        "h1a": "Office and retail fitouts,", "h1b": "delivered on schedule.",
        "sub": "Turnkey design and build for offices, retail, F&B, clinics and showrooms, planned around your opening date.",
        "img": WP + "2025/06/Office-Fitout-services-in-Dubai-2.jpg", "img_alt": "Office fitout by Haus Techs in Dubai",
    },
    "promises": ["Turnkey design and build", "Authority approvals handled", "On-schedule delivery",
                 "Fixed-price quote within 48 hours", "Free 3D design concept with every quotation", "Workmanship warranty on every project"],
    "clients": ("Delivered for", ["Omniyat", "Mazaya Business Avenue JLT", "Acino Pharma", "Ivory Hospital Al Ain", "Amber Clinic", "Modawah Clinic", "Immunotherapy Clinic"]),
    "calc": {"kicker": "Fitout cost calculator", "types": ["Office", "Retail store", "Clinic / medical", "F&B / cafe"], "range": (50, 1500, 10, 250),
             "rates": {"Office": {"standard": 1500, "premium": 2000, "luxury": 2800}, "Retail store": {"standard": 1600, "premium": 2200, "luxury": 3000},
                       "Clinic / medical": {"standard": 2000, "premium": 2600, "luxury": 3400}, "F&B / cafe": {"standard": 1800, "premium": 2400, "luxury": 3200}},
             "min": {"Office": 80000, "Retail store": 80000, "Clinic / medical": 150000, "F&B / cafe": 120000}},
    "calc_wa_js": CALC_WA_EN,
    "form": {"location_label": "Location / building", "location_ph": "e.g. Business Bay, DIFC, Dubai Mall",
             "detail_label": "Type of space", "detail_opts": ["Office fitout", "Office renovation", "Retail store", "Clinic / medical", "F&B / cafe", "Showroom", "Other commercial"]},
    "form_wa_js": form_wa_js("I'd like a quote for a commercial fitout.", "Location / building", "Type of space"),
    "sectors": {
        "h2": "Offices, retail and clinics.",
        "lede": "One team for every kind of commercial space, built around how you trade.",
        "tabs": [
            {"id": "off", "tab": "Offices", "h3": "Workspaces that work harder.",
             "p": "From shell-and-core to the full renovation of an existing office, designed around your team, your clients and your brand.",
             "items": [
                 (WP + "2025/06/Office-Fitout-services-in-Dubai-1.jpg", "Office space planning", "Workspace design and space planning", "Layouts, 3D visualisation and materials built around how your team works: desks, meeting rooms, breakout and client zones."),
                 (WP + "2025/06/Office-Fitout-services-in-Dubai-3.jpg", "Office partitions and ceilings", "Partitions, ceilings, MEP and IT", "Glass and gypsum partitions, ceilings, flooring, power, lighting, AC, data cabling and CCTV, to spec and to code."),
                 (WP + "2025/06/Office-Fitout-services-in-Dubai-2.jpg", "Office reception joinery", "Joinery, reception and branding", "Reception desks, boardroom tables, storage walls and branded features, built in-house so the finish matches the vision."),
             ]},
            {"id": "ret", "tab": "Retail and F&B", "h3": "Stores built to sell.",
             "p": "Boutiques, concept stores, cafes and showrooms, engineered for customer flow, product visibility and your opening date.",
             "items": [
                 (WP + "2025/07/Sienna.jpg", "Sienna retail store", "Store design and customer flow", "Layouts that guide customers through your space, put products in the light and turn footfall into sales."),
                 (WP + "2025/06/3.jpg", "Retail displays", "Displays, counters and signage", "Custom display units, cash counters, feature walls, facade elements and illuminated signage, all built in-house."),
                 (WP + "2024/11/Commercial-Painting.jpg", "Mall works", "Mall approvals and night works", "Mall approvals, hoarding and after-hours shifts planned in from day one, so your opening never slips."),
             ]},
            {"id": "cli", "tab": "Clinics", "h3": "Featured project: Immunotherapy Clinic.",
             "p": "A complete clinic design and fitout, calm, precise and built for patient trust. One of several medical projects alongside Amber Clinic, Modawah Clinic and Ivory Hospital (Al Ain).",
             "items": [
                 ("lp-images/clinic-01.jpg", "Clinic reception with brand wall", "Reception and brand wall", ""),
                 ("lp-images/clinic-02.jpg", "Patient waiting lounge", "Patient lounge", ""),
                 ("lp-images/clinic-04.jpg", "Consultation room", "Consultation rooms", ""),
                 ("work/c-ivory-lobby", "Ivory Hospital Al Ain lobby, 3D concept", "Ivory Hospital, Al Ain", "Lobby and waiting lounge, shown here as the 3D design concept."),
             ]},
        ],
    },
    "journey": journey_en("DM, Civil Defence and DEWA, done",
                          "Dubai Municipality, Civil Defence, DEWA and building management approvals: drawings and permits secured so your opening date never slips."),
    "work": {"h2": "Spaces we've delivered.", "lede": "A walk through the Immunotherapy Clinic, then offices and retail across Dubai. Tap any photo to view.",
             "figs": [
                 ("lp-images/clinic-01.jpg", "Reception and brand wall", "Clinic reception with brand wall"),
                 ("lp-images/clinic-02.jpg", "Patient lounge", "Patient waiting lounge"),
                 ("lp-images/clinic-04.jpg", "Consultation room", ""),
                 ("lp-images/clinic-03.jpg", "Corridor and wayfinding", "Clinic corridor with branding"),
                 ("lp-images/clinic-05.jpg", "Branded feature wall", ""),
                 ("lp-images/clinic-06.jpg", "Staff workspace", ""),
                 ("lp-images/clinic-07.jpg", "Treatment corridor", "Corridor with wood panelling"),
                 ("lp-images/clinic-08.jpg", "Cove-lit circulation", "Marble corridor with cove lighting"),
                 ("lp-images/clinic-09.jpg", "Washrooms", "Clinic washroom"),
                 (WP + "2025/06/Office-Fitout-services-in-Dubai-1.jpg", "Office fitout, delivered", ""),
                 (WP + "2025/06/office-renovation.jpg", "Fitout in progress to handover", ""),
                 (WP + "2025/06/Office-Fitout-services-in-Dubai-4.jpg", "Delivered by our in-house team", ""),
                 (WP + "2025/07/Sienna.jpg", "Retail fitout, Sienna", ""),
                 (WP + "2025/06/office.jpg", "Office interiors, Dubai", ""),
             ]},
    "concepts": {"h2a": "Designed in 3D.", "h2b": "Before we build.",
                 "lede": "Every commercial quotation includes a 3D design concept. Concepts from recent projects:",
                 "figs": [
                     ("work/c-omniyat-boardroom", "Omniyat office, Business Bay: boardroom concept"),
                     ("work/c-mazaya-lounge", "Mazaya Business Avenue, JLT: lounge concept"),
                     ("work/c-ivory-lobby", "Ivory Hospital, Al Ain: lobby concept"),
                     ("work/c-omniyat-reception", "Omniyat office: reception concept"),
                     ("work/c-giahyu-office", "Gia Hyu Land office: workspace concept"),
                     ("work/c-acino-canteen", "Acino Pharma: staff canteen concept"),
                 ]},
    "reviews": {"h2": "What clients say.", "items": [REV["burj"], REV["ivan"], REV["obaid"]]},
    "band": {"h2a": "Your opening date", "h2b": "is our deadline.",
             "p": "Retail and office projects planned backwards from the day you need to trade, and delivered on it.",
             "img": WP + "2025/06/Office-Fitout-services-in-Dubai-1.jpg", "img_alt": "Completed office fitout",
             "gains_h": "A fitout that works as hard as you do.",
             "gains": [("A space that sells", "Retail layouts engineered for customer flow, product visibility and conversion."),
                       ("A workplace people want", "Offices designed for focus, meetings and your company culture."),
                       ("No downtime surprises", "A fixed schedule, approvals handled, after-hours work where the building requires it."),
                       ("Warranty and aftercare", "Our workmanship is covered after handover, and we return for any snags.")]},
    "quote": {"h2": "Tell us about your space."},
    "faq": [
        ("How much does an office or retail fitout cost in Dubai?", "Office fitouts typically start from AED 1,500 per square metre depending on specification, with retail and F&B quoted per scope. After a site visit you receive a detailed, fixed-scope quotation, never vague per-day pricing."),
        ("How long does a fitout take?", "A typical office fitout runs 4 to 8 weeks and retail units 3 to 6 weeks, depending on size and approvals. We plan backwards from your required opening date."),
        ("Do you handle authority approvals?", "Yes. Dubai Municipality, Civil Defence, DEWA and building management approvals are part of our scope, with drawings, NOCs and permits included."),
        ("Can you work around mall or building hours?", "Yes. Night shifts and after-hours work are planned in from day one where the mall or building requires it, so your schedule doesn't slip."),
        ("Do you fit out clinics and medical spaces?", "Yes. Clinic and medical fitouts including branded reception, consultation rooms and patient areas, coordinated with the relevant health authority requirements alongside DM, Civil Defence and DEWA approvals."),
        ("Do you also do office renovations, not just new fitouts?", "Yes. We renovate and upgrade existing offices and stores as well as fitting out shell-and-core units."),
    ] + FAQ_TAIL,
    "final": "Ready to build your space?",
}

# ------------------------------------------------------------------ Arabic villa (RTL)
T_AR = dict(T_EN)
T_AR.update({
    "skip": "انتقل إلى المحتوى",
    "call": "اتصل",
    "nav_cta": 'اطلب <span class="lbl-long">عرض </span>السعر',
    "quote_short": "عرض السعر",
    "wa_cta": "تواصل واتساب",
    "calc_cta": "احسب التكلفة في 30 ثانية",
    "rating": "",
    "proof_label": "هاوس تكس بالأرقام",
    "promises_label": "ما يتضمنه كل مشروع",
    "stats": [(4, "+", "سنوات في دبي"), (200, "+", "مشروع منجز"), (50, "+", "مهندس وفني"), (48, "", "ساعة لعرض السعر")],
    "calc_h": 'اعرف رقمك <span class="it">في 30 ثانية.</span>',
    "calc_lede": "احصل على نطاق تقديري فوري، ثم عرض سعر ثابت خلال 48 ساعة مع تصميم ثلاثي الأبعاد مجاني.",
    "calc_ticks": [
        "تقدير فوري مبني على أسعار مشاريع هاوس تكس الفعلية",
        "عرض سعر ثابت: الرقم الذي تراه هو الرقم الذي تدفعه",
        "تصميم ثلاثي الأبعاد مجاني مع كل عرض سعر",
        "ضمان على جودة التنفيذ في كل مشروع",
    ],
    "calc_mode": "نوع التقدير",
    "mode_reno": "تكلفة التجديد",
    "mode_design": "التصميم فقط",
    "ptype": "نوع العقار",
    "size": "المساحة التقريبية",
    "unit": "م²",
    "finish": "مستوى التشطيب",
    "finishes": [("standard", "قياسي", "جودة أساسية"), ("premium", "مميز", "توقيعنا الخاص"), ("luxury", "فاخر", "تشطيب استثنائي")],
    "est_reno": "التكلفة التقديرية للتجديد",
    "est_design": "رسوم التصميم التقديرية (مفهوم، ثلاثي الأبعاد ومخططات)",
    "cur": "",
    "cur_suffix": " درهم",
    "calc_note": "نطاق استرشادي. عرض السعر الثابت يصدر بعد زيارة موقع مجانية.",
    "calc_wa": "أرسل تقديري عبر واتساب",
    "j_kicker": "كيف نتعامل مع مشروعك",
    "j_h2a": "فريق واحد. رحلة واحدة.",
    "j_h2b": "صفر مفاجآت.",
    "j_lede": "من أول رسالة حتى التسليم: هذا بالضبط ما يحدث، وما تقوم به أنت، وما نتولاه نحن عنك.",
    "you_do": "أنت",
    "we_do": "نحن",
    "view": "عرض الصورة",
    "close": "إغلاق",
    "prev": "الصور السابقة",
    "next": "الصور التالية",
    "v_h2": "لماذا يتوقف عملاؤنا عن المقارنة.",
    "v_lede": "معظم عروض الأسعار تبدو متشابهة على الورق. التجربة خلفها ليست كذلك.",
    "v_old_h": "الطريقة المعتادة",
    "v_new_h": "طريقة هاوس تكس",
    "v_old": ["عدة مقاولين، ولا أحد مسؤول بالكامل", "تسعير باليوم، والرقم يكبر مع الوقت", "أنت تلاحق التحديثات وهم يلاحقون الدفعات",
              "الموافقات والتصاريح تصبح مشكلتك", "تسليم، ثم صمت عند ظهور الملاحظات"],
    "v_new": ["عقد واحد، فريق واحد، مدير مشروع واحد", "سعر ثابت خلال 48 ساعة. ما تراه هو ما تدفعه.", "تصميم ثلاثي الأبعاد مجاني + تحديثات أسبوعية",
              "جميع الموافقات والتصاريح نتولاها نحن", "ضمان جودة التنفيذ وزيارة ما بعد التسليم"],
    "promise": "مرة واحدة، وبالشكل الصحيح. هذا هو وعدنا كله.",
    "q_kicker": "ابدأ الآن",
    "q_lede": "زيارة موقع مجانية، تصميم ثلاثي الأبعاد مجاني، وعرض سعر مفصّل بدون أي التزام. أو راسلنا مباشرة على واتساب.",
    "visit": "احجز زيارة موقع مجانية",
    "visit_sub": "حدد الموعد معنا عبر واتساب",
    "email_l": "راسلنا بالبريد",
    "form_h": "اطلب عرض السعر",
    "form_sub": "زيارة مجانية، تصميم ثلاثي الأبعاد مجاني، بدون التزام.",
    "name": "الاسم",
    "name_ph": "الاسم الكامل",
    "phone": "رقم الهاتف / واتساب",
    "email": "البريد الإلكتروني",
    "contact": "طريقة التواصل المفضلة",
    "contact_opts": ["واتساب", "اتصال هاتفي", "بريد إلكتروني"],
    "optional": "(اختياري)",
    "message": "تفاصيل إضافية",
    "message_ph": "أخبرنا عن الفيلا ومساحتها وما تريد تحقيقه",
    "submit": "اطلب عرض السعر + التصميم المجاني",
    "or": "أو",
    "send_wa": "أرسل عبر واتساب",
    "form_note": "نرد في نفس يوم العمل. نستخدم بياناتك فقط لإعداد عرض السعر.",
    "err_name": "يرجى كتابة اسمك.",
    "err_phone": "يرجى كتابة رقم هاتف يمكننا التواصل معك عليه.",
    "err_email": "يبدو أن البريد الإلكتروني غير مكتمل.",
    "err_location": "يرجى كتابة المنطقة.",
    "faq_h": "",
    "final_lede": "استشارة مجانية، زيارة موقع مجانية، وعرض سعر ثابت ومفصّل.",
    "company": "هاوس تكس للمقاولات الفنية ذ.م.م",
    "address": "مبنى برنسس كارز، مكتب 14-27، شارع الشيخ زايد، القوز الأولى، دبي",
    "tagline": "تجديد · تجهيز · تصميم داخلي",
    "quick": "تواصل سريع",
    "before": "قبل",
    "after": "بعد",
    "ba_slider": "اسحب للمقارنة بين قبل وبعد",
    "play": "شاهد الفيديو",
})

VILLA_AR = {
    "file": "villa-renovation-dubai-ar.html", "lang": "ar", "rtl": True, "T": T_AR,
    "title": "تجديد الفلل في دبي | عرض سعر ثابت خلال 48 ساعة | هاوس تكس",
    "desc": "تجديد فلل كامل في دبي بفريق واحد: تصميم، موافقات، تنفيذ وتسليم. عرض سعر ثابت خلال 48 ساعة مع تصميم ثلاثي الأبعاد مجاني. ضمان على جودة التنفيذ.",
    "subject": "New Lead - Arabic Villa LP",
    "source": "Arabic Villa Landing Page",
    "hidden_order": "source-first",
    "wa_url": wa("مرحباً هاوس تكس، أريد عرض سعر لتجديد فيلا"),
    "visit_url": wa("مرحباً هاوس تكس، أريد حجز زيارة موقع مجانية للفيلا"),
    "hero_form": False,
    "hero": {
        "kicker": "شركة تجديد فلل في دبي",
        "h1a": "جدّد فيلتك مرة واحدة،", "h1b": "وبالشكل الصحيح.",
        "sub": "فريق واحد يتولى كل شيء: التصميم، الموافقات، التنفيذ والتسليم. بدون مقاولين متعددين، بدون تكاليف مفاجئة، وبموعد تسليم ثابت.",
        "img": "lp-images/design-13.jpg", "img_alt": "صالة معيشة فاخرة من تصميم هاوس تكس",
    },
    "promises": ["عرض سعر ثابت خلال 48 ساعة", "تصميم ثلاثي الأبعاد مجاني مع كل عرض سعر", "ضمان على جودة التنفيذ في كل مشروع",
                 "مدير مشروع واحد", "عقد واحد، فريق واحد", "جميع الموافقات علينا"],
    "calc": {"kicker": "حاسبة تكلفة التجديد", "types": ["فيلا", "تاون هاوس"], "range": (200, 1200, 10, 400),
             "rates": {"فيلا": {"standard": 1800, "premium": 2400, "luxury": 3200}, "تاون هاوس": {"standard": 1700, "premium": 2200, "luxury": 3000}}},
    "calc_wa_js": "function(type,sqm,finish,est){return \"مرحباً هاوس تكس، استخدمت حاسبة التكلفة.\\nالنوع: \"+type+\"\\nالمساحة: \"+sqm+\" م²\\nالتشطيب: \"+finish+\"\\nالتقدير: \"+est+\"\\nأرغب في عرض سعر ثابت.\";}",
    "form": {"location_label": "المنطقة", "location_ph": "مثال: البراري، المرابع العربية، تلال الإمارات", "location_required": False,
             "detail_label": "نوع المشروع", "detail_opts": ["تجديد فيلا كامل", "تجديد مطبخ وحمامات", "تصميم داخلي فقط", "أخرى"]},
    "form_wa_js": "function(d){return \"مرحباً هاوس تكس، أريد عرض سعر لتجديد فيلا.\\nالاسم: \"+d.name+\"\\nالهاتف: \"+d.phone+\"\\nالمنطقة: \"+d.location+\"\\nنوع المشروع: \"+d.detail+(d.message?\"\\nملاحظة: \"+d.message:\"\");}",
    "journey": [
        {"h3": "تتواصل معنا", "p": "نموذج، واتساب، أو حاسبة التكلفة، كما يناسبك.", "you": "دقيقتان من وقتك.", "we": "نرد في نفس يوم العمل ونحجز زيارة موقع مجانية."},
        {"h3": "زيارة الموقع والاستماع", "p": "نتجول في الفيلا معك ونستمع لطريقة معيشتك فيها.", "you": "أرِنا المكان وأخبرنا بالحلم.", "we": "نقيس كل شيء وننصحك بصدق، حتى بما لا يستحق الإنفاق."},
        {"h3": "عرض سعر ثابت + تصميم ثلاثي الأبعاد مجاني", "p": "رقم واحد واضح وتصميم لمساحتك، قبل أي التزام.", "you": "تراجع عرض سعر مفصلاً وثابتاً.", "we": "نطاق كامل وأرقام حقيقية. لا تسعير باليوم، أبداً."},
        {"h3": "الموافقات والتصاريح علينا", "p": "الأوراق مهمتنا، لا مهمتك.", "you": "لا شيء. حرفياً لا شيء.", "we": "موافقات المجتمع والمطوّر والجهات الرسمية: مخططات وتصاريح نؤمّنها بالكامل."},
        {"h3": "التنفيذ بفريق واحد", "p": "فرقنا الخاصة، مدير مشروع واحد، وجدول زمني ثابت.", "you": "تحديث أسبوعي من شخص واحد تعرفه بالاسم.", "we": "تنفيذ داخلي، إشراف يومي، وضبط للغبار والضوضاء.",
         "photos": [("work/crew-cladding", "فني من هاوس تكس يركّب تكسية الجدار"), ("work/crew-level", "فني من هاوس تكس يضبط استواء لوح الجدار"), ("work/crew-joinery", "نجار من هاوس تكس يركّب خزائن المطبخ")],
         "photos_cap": "فرقنا الخاصة في الموقع، مشروع تجديد فيلا في ليفينج ليجندز."},
        {"h3": "التسليم، وبضمان", "p": "تسليم خالٍ من الملاحظات مع ضمان جودة التنفيذ.", "you": "انتقل وعِش.", "we": "جولة نهائية معاً، ضمان مكتوب، ونعود إذا احتجتنا يوماً."},
    ],
    "before_after": {
        "h2a": "فيلا G17، الواحة.", "h2b": "قبل وبعد.",
        "lede": "تجديد فيلا كامل نفّذه فريقنا. اسحب الخط للمقارنة بين الغرف نفسها قبل البدء وعند التسليم.",
        "note": "صور حقيقية من موقع المشروع، وليست تصاميم ثلاثية الأبعاد.",
        "pairs": [("غرفة نوم", "work/g17-before-bedroom-2", "work/g17-bedroom", "غرفة نوم بأبواب فرنسية"),
                  ("غرفة النوم الرئيسية", "work/g17-before-bedroom", "work/g17-bedroom-wardrobe", "غرفة نوم مع خزانة مدمجة"),
                  ("الحمّام", "work/g17-before-bath", "work/g17-after-bath", "حمّام")],
    },
    "work": {"h2": "مساحات صمّمناها ونفّذناها.", "lede": "مشاريع حقيقية نفّذتها فرقنا، منها فيلا 91 في العين وفيلا G17 في الواحة. اضغط على أي صورة لعرضها.",
             "figs": [
                 ("work/v91-shower", "فيلا 91، العين: حمّام رئيسي بالترافرتين", ""),
                 ("work/g17-bedroom-wardrobe", "فيلا G17، الواحة: غرفة نوم وخزائن", ""),
                 ("work/v91-bath-vanity", "فيلا 91، العين: مغسلة معلّقة ودش", ""),
                 ("work/g17-living", "فيلا G17، الواحة: صالة المعيشة", ""),
                 ("lp-images/design-13.jpg", "صالة معيشة فاخرة", ""),
                 ("lp-images/design-09.jpg", "صالة بسقف مزدوج", ""),
                 ("lp-images/design-14.jpg", "غرفة نوم رئيسية", ""),
                 (WP + "2025/06/villa-renovation.jpg", "تجديد فيلا في دبي", ""),
                 ("lp-images/design-12.jpg", "جدار ترافرتين", ""),
                 (WP + "2025/06/villa-interior.jpg", "تصميم داخلي لفيلا", ""),
             ]},
    "concepts": {"h2a": "تصميم ثلاثي الأبعاد مجاني.", "h2b": "قبل أي التزام.",
                 "lede": "كل عرض سعر يتضمن تصميماً ثلاثي الأبعاد لفيلتك، لترى النتيجة قبل بدء العمل. من أحدث تصاميم الاستوديو:",
                 "figs": [("work/c-villa-living", "تصميم ثلاثي الأبعاد: صالة بسقف مزدوج"), ("work/c-villa-bedroom", "تصميم ثلاثي الأبعاد: غرفة نوم رئيسية"),
                          ("work/c-villa-vanity", "تصميم ثلاثي الأبعاد: مغسلة رخامية"), ("work/c-villa-dining", "تصميم ثلاثي الأبعاد: غرفة طعام"),
                          ("work/c-villa-bedroom-2", "تصميم ثلاثي الأبعاد: غرفة نوم"), ("work/c-barari-living", "تصميم ثلاثي الأبعاد: فيلا في البراري")]},
    "quote": {"h2": "عرض سعرك الثابت خلال 48 ساعة."},
    "final": "جاهز لتجديد فيلتك؟",
}

PAGES = [VILLA, APARTMENT, PALM, COMMERCIAL, VILLA_AR]

THANK_YOU = {
    "file": "thank-you.html", "lang": "en", "T": T_EN,
    "title": "Thank You | Haus Techs",
    "h1a": "Thank you.", "h1b": "Your enquiry is with our team.",
    "p": "We'll contact you the same working day to arrange your free consultation and site visit. Want to move faster? Message us on WhatsApp now.",
    "wa_url": wa("Hi Haus Techs, I just sent an enquiry through your website."),
    "back": "Back to haustechs.ae",
}
